---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hongyiheng.
--- DateTime: 2021/1/26 16:58
---
if redis.call("get",KEYS[1]) == ARGV[1] then
    return redis.call("del",KEYS[1])
else
    return 0
end